# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

#env:
  #variables:
     # key: "There are no variables"
  #parameter-store:
     # key: "There are no variables"

phases:
  install:
    runtime-versions:
       python: 3.9
    #commands:
      # - There are no build commands
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -e .
#  build:
#    commands:
#      - pytest tests/currency_table_test.py
#      - pytest tests/integration/ -rfs
  post_build:
    commands:
      - python setup.py build
artifacts:
  discard-paths: yes
  base-directory: build
#cache:
  #paths:
    # - We don't currently cache anything

